name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Change this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "8.0.x" # Adjust this to your .NET version

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --output ./output

      - name: Publish
        run: dotnet publish --configuration Release --output ./output

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output # This points to your output directory with MyAPIApp.exe and runtimes folder
